lib/webbait_web/router.ex
defmodule WebBaitWeb.Router do
  use WebBaitWeb, :router

  import WebBaitWeb.UserAuth

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {WebBaitWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  # Other scopes may use custom stacks.
  scope "/api", WebBaitWeb do
    pipe_through :api
    post "/agents", AgentController, :create
    post "/agents/token", AgentController, :token
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)

      live_dashboard("/live_dashboard", metrics: WebBaitWeb.Telemetry)
    end
  end

  ## Authentication routes

  scope "/", WebBaitWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])

    get("/", UserSessionController, :new)
    post("/", UserSessionController, :create)
  end

  scope "/", WebBaitWeb do
    pipe_through([:browser, :require_authenticated_user])

    live("/dashboard", MainLive.Index, :index)
    live("/settings", SettingsLive.Index, :index)
    live("/users", UsersLive.Users, :index)
    live("/users/new", UsersLive.Users, :new)
    live("/users/delete/:id", UsersLive.Users, :delete)
    live "/agents", AgentLive.Index, :index
    live "/agents/:id", AgentLive.Webrtc, :index
    live "/agents/:id/theater", AgentLive.Webrtc, :theater
    live "/agents/:id/commands", AgentLive.Commands, :index
    live "/agents/:id/activities", AgentLive.Activities, :index
  end

  scope "/", WebBaitWeb do
    pipe_through([:browser])

    delete("/logout", UserSessionController, :delete)
  end
end

lib/webbait_web/views/layout_view.ex
defmodule WebBaitWeb.LayoutView do
  import Plug.Conn
  alias Phoenix.LiveView.JS

  use WebBaitWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/webbait_web/templates/layout/_user_menu.html.heex
<%= if @current_user do %>
  <div class="grow"></div>
  <button
    type="button"
    class="flex p-1 mr-3 text-sm rounded-full bg-slate-700 hover:bg-slate-600 transition duration-300 order-last"
    id="user-menu-button"
    aria-expanded="false"
    data-dropdown-toggle="user-dropdown"
    data-dropdown-placement="bottom">
    <span class="sr-only">Open user menu</span>
    <div class="w-8 h-8 rounded-full flex">
      <b class="m-auto">
        <%= String.upcase("#{String.at(@current_user.firstName, 0)}#{String.at("#{@current_user.lastName}", 0)}") %>
      </b>
    </div>
  </button>
  <!-- Dropdown menu -->
  <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
    <div class="px-4 py-3">
      <span class="block text-sm text-gray-900 dark:text-white">
        <%= "#{@current_user.firstName} #{@current_user.lastName}" %>
        <p class="ml-1 inline text-gray-500">(<%= @current_user.username %>)</p>
      </span>
      <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400"><%= @current_user.email %></span>
    </div>
    <ul class="py-2" aria-labelledby="user-menu-button">
      <li>
        <%= live_redirect "Settings", replace: true, to: Routes.settings_index_path(@conn, :index), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
      </li>
      <li>
        <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
      </li>
    </ul>
  </div>
<% end %>

lib/webbait_web/templates/layout/app.html.heex
<main class="flex flex-col w-full h-full">
  <div class="p-2">
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  </div>
  <%= @inner_content %>
</main>

lib/webbait_web/templates/layout/drawer.html.heex
<div
  id="drawer-backdrop"
  class="fixed top-0 left-0 z-40 h-screen p-4 overflow-y-auto transition-transform -translate-x-full bg-white w-80 dark:bg-gray-800"
  tabindex="-1"
  aria-labelledby="drawer-backdrop-label">
  <div class="relative w-full h-8 flex flex-row">
    <div class="grow"></div>
    <button
      type="button"
      data-drawer-hide="drawer-backdrop"
      aria-controls="drawer-backdrop"
      class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded text-md w-8 h-8 dark:hover:bg-gray-600 dark:hover:text-white">
      <i class="fa-solid fa-xmark"></i>
      <span class="sr-only">Close drawer</span>
  </button>
  </div>
  <div class="py-4 overflow-y-auto">
    <ul class="space-y-2">
      <li>
        <%= live_redirect to: Routes.main_index_path(@conn, :index), class: "flex items-center p-2 text-base font-normal text-gray-900 rounded dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700" do %>
          <i class="fa-solid fa-house"></i>
          <span class="ml-3">Dashboard</span>
        <% end %>
      </li>
      <li>
        <%= live_redirect to: Routes.users_users_path(@conn, :index), class: "flex items-center p-2 text-base font-normal text-gray-900 rounded dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700" do %>
          <i class="fa-solid fa-users"></i>
          <span class="ml-3">Users</span>
        <% end %>
      </li>
      <li>
        <%= live_redirect to: Routes.agent_index_path(@conn, :index), class: "flex items-center p-2 text-base font-normal text-gray-900 rounded dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700" do %>
          <i class="fa-solid fa-robot"></i>
          <span class="ml-3">Agents</span>
        <% end %>
      </li>
    </ul>
  </div>
</div>

lib/webbait_web/templates/layout/live.html.heex
<main id="live" class="flex flex-col w-full h-full">
  <div class="p-2 px-[25%] flex flex-col justify-center">
    <%= if live_flash(@flash, :info) do %>
      <div
        id="alert-info"
        class="flex p-4 mb-4 text-blue-800 border-t-4 border-blue-300 bg-blue-50 dark:text-blue-400 dark:bg-gray-800 dark:border-blue-800"
        role="alert">
        <div class="ml-3 text-sm font-medium"><%= live_flash(@flash, :info) %></div>
        <button
          type="button"
          class="ml-auto -mx-1.5 -my-1.5 bg-blue-50 text-blue-500 rounded focus:ring-2 focus:ring-blue-400 p-1.5 hover:bg-blue-200 inline-flex h-8 w-8 dark:bg-gray-800 dark:text-blue-400 dark:hover:bg-gray-700"
          data-dismiss-target="#alert-info"
          phx-click="lv:clear-flash"
          phx-value-key="info"
          aria-label="Close">
          <span class="sr-only">Dismiss</span>
          <i class="fa-solid fa-xmark m-auto"></i>
        </button>
      </div>
    <% end %>
    <%= if live_flash(@flash, :error) do %>
      <div
        id="alert-error"
        class="flex p-4 mb-4 text-red-800 border-t-4 border-red-300 bg-red-50 dark:text-red-400 dark:bg-gray-800 dark:border-red-800"
        role="alert">
        <div class="ml-3 text-sm font-medium"><%= live_flash(@flash, :error) %></div>
        <button
          type="button"
          class="ml-auto -mx-1.5 -my-1.5 bg-red-50 text-red-500 rounded focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200 inline-flex h-8 w-8 dark:bg-gray-800 dark:text-red-400 dark:hover:bg-gray-700"
          data-dismiss-target="#alert-error"
          phx-click="lv:clear-flash"
          phx-value-key="error"
          aria-label="Close">
          <span class="sr-only">Dismiss</span>
          <i class="fa-solid fa-xmark m-auto"></i>
        </button>
      </div>
    <% end %>
    <%= if live_flash(@flash, :success) do %>
      <div
        id="alert-success"
        class="flex p-4 mb-4 text-green-800 border-t-4 border-green-300 bg-green-50 dark:text-green-400 dark:bg-gray-800 dark:border-green-800"
        role="alert">
        <div class="ml-3 text-sm font-medium"><%= live_flash(@flash, :success) %></div>
        <button
          type="button"
          class="ml-auto -mx-1.5 -my-1.5 bg-green-50 text-green-500 rounded focus:ring-2 focus:ring-green-400 p-1.5 hover:bg-green-200 inline-flex h-8 w-8 dark:bg-gray-800 dark:text-green-400 dark:hover:bg-gray-700"
          data-dismiss-target="#alert-success"
          phx-click="lv:clear-flash"
          phx-value-key="success"
          aria-label="Close">
          <span class="sr-only">Dismiss</span>
          <i class="fa-solid fa-xmark m-auto"></i>
        </button>
      </div>
    <% end %>
    <%= if live_flash(@flash, :warning) do %>
      <div id="alert-warning" class="flex p-4 mb-4 text-yellow-800 border-t-4 border-yellow-300 bg-yellow-50 dark:text-yellow-300 dark:bg-gray-800 dark:border-yellow-800" role="alert">
        <div class="ml-3 text-sm font-medium"><%= live_flash(@flash, :warning) %></div>
        <button
          type="button"
          class="ml-auto -mx-1.5 -my-1.5 bg-yellow-50 text-yellow-500 rounded focus:ring-2 focus:ring-yellow-400 p-1.5 hover:bg-yellow-200 inline-flex h-8 w-8 dark:bg-gray-800 dark:text-yellow-300 dark:hover:bg-gray-700"
          data-dismiss-target="#alert-warning"
          phx-click="lv:clear-flash"
          phx-value-key="warning"
          aria-label="Close">
          <span class="sr-only">Dismiss</span>
          <i class="fa-solid fa-xmark m-auto"></i>
        </button>
      </div>
    <% end %>
  </div>

  <%= @inner_content %>
</main>

lib/webbait_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= if (get_session(@conn, :user_token)) do %><meta name="token" content={Base.encode64(get_session(@conn, :user_token))}><% end %>
    <%= live_title_tag assigns[:page_title] || "WebBait", suffix: " · WebBait" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="dark:bg-slate-900 dark:text-white grid grid-rows-[56px_calc(100%-56px)]">
    <header class="p-2 flex gap-2 bg-fuchsia-700 dark:bg-fuchsia-900 text-white shadow-md shadow-gray-400 dark:shadow-slate-700">
      <div class="text-center">
        <%= if (@current_user) do %>
          <button
            data-tooltip-target="drawer-toggle-tooltip"
            class="text-white rounded w-[40px] h-[40px] p-2 hover:bg-black/30"
            type="button"
            data-drawer-target="drawer-backdrop"
            data-drawer-show="drawer-backdrop"
            data-drawer-backdrop="true"
            aria-controls="drawer-backdrop">
            <i class="fa-solid fa-bars"></i>
          </button>
          <div id="drawer-toggle-tooltip" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
            Toggle Drawer
            <div class="tooltip-arrow" data-popper-arrow></div>
          </div>
        <% end %>
      </div>
      <p data-tooltip-target="dark-mode-toggle-tooltip" class="p-2 w-[40px] h-[40px] text-center rounded hover:bg-fuchsia-500 dark:hover:bg-fuchsia-700 cursor-pointer" phx-click={JS.dispatch("toggleDarkMode")} id="darkModeToggle">
        <i class="fa-solid fa-moon"></i>
      </p>
      <div id="dark-mode-toggle-tooltip" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
        Toggle Dark Mode
        <div class="tooltip-arrow" data-popper-arrow></div>
      </div>
      <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
        <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "bg-sky-700 hover:bg-sky-600 transition duration-300 p-2 rounded" %>
      <% end %>
      <%= render "_user_menu.html", assigns %>
      <%= render "drawer.html", assigns %>
    </header>
    <%= @inner_content %>
  </body>
</html>